apiVersion: autoscaling.4pd.io/v1alpha1
kind: LLMScaler
metadata:
  labels:
    app.kubernetes.io/name: llmscaleoperator
    app.kubernetes.io/managed-by: kustomize
  name: llmscaler-sample
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vllm-opt-125m
  serverAddress: "http://prometheus-operated.monitoring.svc:9090"
  selector:
    model_name: "facebook/opt-125m"
  minReplicas: 1
  maxReplicas: 5
  syncPeriodSeconds: 15
  retryPeriodSeconds: 10
  metrics:
    - type: KVCacheUtilization
      targetAverageValue: "80%"
  scaleDown:
    stabilizationWindowSeconds: 300
    behavior: CacheAware
    deletionCostQuery: 'vllm:kv_cache_usage_perc{namespace="default"} * 100'
